(() => {
  const weatherButtons=[...document.querySelectorAll('.weather')],note=document.getElementById('high-note'),brand=document.getElementById('brand-message'),mainTitle=document.querySelector('.brand h1'),classLabel=document.getElementById('student-class-label'),weatherKicker=document.getElementById('weather-kicker'),weatherTitle=document.getElementById('weather-title'),weatherGuide=document.getElementById('weather-guide'),routineKicker=document.getElementById('routine-kicker'),routineTitle=document.getElementById('routine-title'),celebration=document.getElementById('completion-celebration'),celebrationTitle=document.getElementById('celebration-title'),celebrationMessage=document.getElementById('celebration-message'),closeButton=document.getElementById('celebration-close'),nextButton=document.getElementById('next-step-button'),guideTitle=document.getElementById('child-guide-title'),guideDetail=document.getElementById('child-guide-detail'),routinePanel=document.getElementById('routine-panel');
  const weatherLow=['はれ','くもり','あめ','かみなり'],weatherHigh=['晴れ','曇り','雨','雷'];let celebrated=false,noteTimer=null,mode='low',selectedWeather=null,lastProgress={done:0,total:0};
  const classText=value=>{const m=String(value||'').match(/^(\d+)[-_](\d+)$/);return m?`${m[1]}年${m[2]}組`:String(value||'クラス');};
  function paintGuide(){const high=mode==='high',allDone=lastProgress.total>0&&lastProgress.done===lastProgress.total,ready=!!selectedWeather&&allDone;if(!selectedWeather){nextButton.disabled=true;nextButton.innerHTML=high?'準備へ <span aria-hidden="true">›</span>':'つぎへ <span aria-hidden="true">›</span>';guideTitle.textContent=high?'まず、今の状態を選ぼう':'まず きもちを えらぼう！';guideDetail.textContent=high?'選んだら朝の準備へ進みます':'えらんだら、あさの じゅんびへ すすもう';return;}if(ready){nextButton.disabled=false;nextButton.innerHTML=high?'終了 <span aria-hidden="true">✓</span>':'おわり <span aria-hidden="true">✓</span>';guideTitle.textContent=high?'心の天気と朝の準備がすべて終わりました':'こころの てんきも じゅんびも できたね！';guideDetail.textContent=high?'「終了」を押して朝のチェックインを確定します':'「おわり」を おして かんりょう！';return;}nextButton.disabled=false;nextButton.innerHTML=high?'準備へ <span aria-hidden="true">›</span>':'つぎへ <span aria-hidden="true">›</span>';guideTitle.textContent=high?'次は朝の準備を進めよう':'つぎは あさの じゅんび！';guideDetail.textContent=high?`${lastProgress.done}/${lastProgress.total} 完了`:`${lastProgress.done}/${lastProgress.total} できたよ`;}
  weatherButtons.forEach((button,index)=>{const weather=['sunny','cloudy','rainy','thunder'][index];button.dataset.weather=weather;button.setAttribute('aria-pressed','false');button.addEventListener('click',()=>{weatherButtons.forEach(item=>{item.classList.remove('selected');item.setAttribute('aria-pressed','false');});button.classList.add('selected');button.setAttribute('aria-pressed','true');selectedWeather=weather;celebrated=false;window.MorningTasks?.setWeather(weather);window.MorningTasks?.setFinished(false);paintGuide();});});
  note?.addEventListener('input',()=>{clearTimeout(noteTimer);noteTimer=setTimeout(()=>window.MorningTasks?.setNote(note.value),350);});
  nextButton?.addEventListener('click',()=>{if(nextButton.disabled)return;const allDone=lastProgress.total>0&&lastProgress.done===lastProgress.total;if(selectedWeather&&allDone){window.MorningTasks?.setFinished(true);showCelebration();return;}routinePanel?.scrollIntoView({behavior:'smooth',block:'start'});routinePanel?.classList.add('attention');setTimeout(()=>routinePanel?.classList.remove('attention'),900);});
  function applyMode(nextMode){mode=nextMode==='high'?'high':'low';document.documentElement.dataset.gradeMode=mode;weatherButtons.forEach((button,index)=>{const label=button.querySelector('b');if(label)label.textContent=(mode==='high'?weatherHigh:weatherLow)[index];});if(mode==='high'){if(mainTitle)mainTitle.textContent='朝のチェックイン';brand.textContent='おはよう。今日のスタートを自分で整えよう';weatherKicker.textContent='今の自分の状態を';weatherTitle.textContent='天気で表すと？';if(weatherGuide)weatherGuide.textContent='今の自分にいちばん近いマスコットを選んでください';routineKicker.textContent='朝の準備';routineTitle.textContent='見通しをもって進めよう';if(note)note.placeholder='今の気持ちや、先生に伝えたいこと（書かなくてもOK）';}else{if(mainTitle)mainTitle.textContent='あさの チェックイン';brand.textContent='おはよう！ きょうも いいスタートを';weatherKicker.textContent='きょうの こころは';weatherTitle.textContent='どんな てんき？';if(weatherGuide)weatherGuide.textContent='いまの きもちに いちばん ちかい マスコットを えらんでね';routineKicker.textContent='あさの じゅんび';routineTitle.textContent='できたら タッチ！';}paintGuide();}
  function showCelebration(){if(!celebration||celebrated)return;celebrated=true;celebrationTitle.textContent=mode==='high'?'朝のチェックイン 終了！':'あさの チェックイン おわり！';celebrationMessage.textContent=mode==='high'?'今日も自分のペースで、いい一日にしよう。':'きょうも いい一日に しよう！';celebration.hidden=false;requestAnimationFrame(()=>celebration.classList.add('show'));}
  function hideCelebration(){if(!celebration)return;celebration.classList.remove('show');setTimeout(()=>{celebration.hidden=true;},180);}closeButton?.addEventListener('click',hideCelebration);
  window.addEventListener('morning-config-loaded',e=>{applyMode(e.detail?.mode);if(classLabel)classLabel.textContent=classText(e.detail?.classId);celebrated=false;window.MorningTasks?.setFinished(false);});
  window.addEventListener('morning-task-progress',e=>{lastProgress=e.detail||{done:0,total:0};const {done,total}=lastProgress;if(done<total){celebrated=false;window.MorningTasks?.setFinished(false);}paintGuide();});
})();
