(() => {
  const STORAGE_KEY='school-checkin:published-config', DEVICE_KEY='school-checkin:device-id', PROFILE_KEY='school-checkin:device-profile', CHANNEL_NAME='school-checkin-config';
  const state={config:null,completed:new Set(),socket:null,reconnectTimer:null,online:false,weather:null,note:'',finished:false};
  const grid=document.getElementById('task-grid'),doneEl=document.getElementById('task-done'),totalEl=document.getElementById('task-total'),startLabel=document.getElementById('start-time-label'),endLabel=document.getElementById('end-time-label'),syncStatus=document.getElementById('sync-status'),deviceLabel=document.getElementById('device-label');
  const channel='BroadcastChannel'in window?new BroadcastChannel(CHANNEL_NAME):null;
  const safe=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]||c));
  const ARTWORK={
    'contact-book':'assets/images/tasks/contact-book.svg',
    'desk':'assets/images/tasks/desk.svg',
    'reading':'assets/images/tasks/reading.svg',
    'health':'assets/images/tasks/temperature.svg',
    'submission':'assets/images/tasks/submission.svg'
  };
  function profile(){try{return JSON.parse(localStorage.getItem(PROFILE_KEY)||'null');}catch(_){return null;}}
  function deviceId(){const p=profile();if(p?.deviceId){localStorage.setItem(DEVICE_KEY,p.deviceId);return p.deviceId;}let v=localStorage.getItem(DEVICE_KEY);if(!v){v=`tablet-${Math.random().toString(36).slice(2,8)}`;localStorage.setItem(DEVICE_KEY,v);}return v;}
  function paintDeviceLabel(){const p=profile();if(deviceLabel)deviceLabel.textContent=p?.label||'未設定のタブレット';}
  function progress(){const active=(state.config?.tasks||[]).filter(t=>t.enabled);return{done:active.filter(t=>state.completed.has(t.id)).length,total:active.length};}
  function sendState(){if(state.socket?.readyState!==WebSocket.OPEN)return;const p=progress();state.socket.send(JSON.stringify({type:'student-state',deviceId:deviceId(),weather:state.weather,note:state.note.slice(0,80),done:p.done,total:p.total,finished:state.finished===true}));}
  function paintProgress(){const p=progress();doneEl.textContent=String(p.done);totalEl.textContent=String(p.total);window.dispatchEvent(new CustomEvent('morning-task-progress',{detail:p}));}
  function taskLabel(task){return state.config?.mode==='high'?(task.labelHigh||task.label||'やること'):(task.label||'やること');}
  function minuteLabel(task){const n=Math.max(1,Number(task.minutes)||1);return state.config?.mode==='high'?`${n}分`:`${n}ぷん`;}
  function helperLabel(task){if(state.config?.mode==='high')return task.helperHigh||task.helper||'';return task.helper||'';}
  function artworkFor(task){return task.artwork||ARTWORK[task.id]||'';}
  function makeTaskCard(task,index){const b=document.createElement('button');b.className=`task-card task-${task.accent||'blue'}`;b.type='button';b.dataset.taskId=task.id;const done=state.completed.has(task.id),helper=helperLabel(task),art=artworkFor(task);b.classList.toggle('done',done);b.setAttribute('aria-pressed',String(done));const visual=art?`<span class="task-icon task-art"><img src="${safe(art)}" alt="" onerror="this.parentElement.classList.remove('task-art');this.remove();this.parentElement.textContent='${safe(task.icon||'⭐')}'"></span>`:`<span class="task-icon">${safe(task.icon||'⭐')}</span>`;b.innerHTML=`<span class="task-step" aria-hidden="true">${index+1}</span>${visual}<span class="task-copy"><span class="task-label">${safe(taskLabel(task))}</span>${helper?`<span class="task-helper">${safe(helper)}</span>`:''}<small>${minuteLabel(task)}</small></span><span class="task-check">✓</span>`;b.onclick=()=>{state.completed.has(task.id)?state.completed.delete(task.id):state.completed.add(task.id);state.finished=false;b.classList.toggle('done',state.completed.has(task.id));b.setAttribute('aria-pressed',String(state.completed.has(task.id)));paintProgress();sendState();};return b;}
  function ack(version){if(state.socket?.readyState===WebSocket.OPEN)state.socket.send(JSON.stringify({type:'config-ack',version:Number(version)||0,deviceId:deviceId()}));}
  function render(config,source='local'){const ids=new Set((config.tasks||[]).map(t=>t.id));state.completed=new Set([...state.completed].filter(id=>ids.has(id)));state.finished=false;state.config=config;localStorage.setItem(STORAGE_KEY,JSON.stringify(config));grid.innerHTML='';const active=config.tasks.filter(t=>t.enabled);grid.classList.toggle('task-grid-many',active.length>4);active.forEach((t,i)=>grid.appendChild(makeTaskCard(t,i)));const high=config.mode==='high';startLabel.textContent=high?`${config.startTime} 開始`:`${config.startTime} スタート`;endLabel.textContent=high?`${config.endTime} 朝の会`:`${config.endTime} あさのかい`;document.documentElement.dataset.gradeMode=config.mode||'low';window.MorningTimer?.setSchedule({start:config.startTime,end:config.endTime,mode:config.mode||'low'});paintProgress();if(syncStatus){if(source==='teacher')syncStatus.textContent=high?'先生の変更を受け取りました':'せんせいの へんこうを うけとりました';else syncStatus.textContent=state.online?(high?'先生と接続中':'せんせいと つながっています'):(high?'オフラインでも使えます':'オフラインでも つかえます');if(source==='teacher')setTimeout(()=>{syncStatus.textContent=state.online?(high?'先生と接続中':'せんせいと つながっています'):(high?'オフラインでも使えます':'オフラインでも つかえます');},3500);}window.dispatchEvent(new CustomEvent('morning-config-loaded',{detail:config}));sendState();}
  function connectSocket(classId){if(!/^https?:$/.test(location.protocol)){state.online=false;return;}clearTimeout(state.reconnectTimer);if(state.socket){state.socket.onclose=null;state.socket.close();}const protocol=location.protocol==='https:'?'wss:':'ws:';const socket=new WebSocket(`${protocol}//${location.host}/ws?classId=${encodeURIComponent(classId)}&deviceId=${encodeURIComponent(deviceId())}`);state.socket=socket;socket.onopen=()=>{state.online=true;if(syncStatus)syncStatus.textContent=state.config?.mode==='high'?'先生と接続中':'せんせいと つながっています';sendState();};socket.onmessage=e=>{try{const m=JSON.parse(e.data);if(m.type==='config-published'&&m.config){render(m.config,'teacher');ack(m.config.version);}else if(m.type==='hello'){if(m.config&&(!state.config||Number(m.config.version)>Number(state.config.version||0)))render(m.config,'teacher');ack((m.config||state.config||{}).version);sendState();}}catch(_){}};socket.onclose=()=>{state.online=false;if(syncStatus)syncStatus.textContent=state.config?.mode==='high'?'再接続しています… 現在の画面はそのまま使えます':'つなぎなおしています… いまの画面はそのまま使えます';state.reconnectTimer=setTimeout(()=>connectSocket(classId),3000);};socket.onerror=()=>socket.close();}
  function readStored(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');}catch(_){return null;}}
  async function load(){paintDeviceLabel();const params=new URLSearchParams(location.search),demo=params.get('demo')==='1';let p=profile();if(!p&&demo){p={classId:'1-1',deviceId:'1-1-07',label:'1年1組 7番（デモ）'};}if(!p&&!demo&&location.protocol!=='file:'){location.replace('setup.html');return;}const stored=readStored(),classId=p?.classId||stored?.classId||'1-1';let config=null;try{const r=await fetch(`/api/classes/${encodeURIComponent(classId)}/today`,{cache:'no-store'});if(r.ok){config=await r.json();state.online=true;}}catch(_){}if(!config&&stored&&(!p||stored.classId===classId))config=stored;if(!config){try{const r=await fetch('data/tasks.json',{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);config=await r.json();config.classId=classId;}catch(e){console.error(e);if(syncStatus)syncStatus.textContent='せっていを よみこめませんでした';return;}}if(demo&&params.get('mode')==='high')config={...config,mode:'high'};render(config,'local');if(deviceLabel&&demo)deviceLabel.textContent=p.label;connectSocket(classId);}
  channel?.addEventListener('message',e=>{if(e.data?.type!=='config-published'||!e.data.config)return;const p=profile();if(p&&e.data.config.classId!==p.classId)return;render(e.data.config,'teacher');});
  window.addEventListener('storage',e=>{if(e.key===PROFILE_KEY){paintDeviceLabel();return;}if(e.key!==STORAGE_KEY||!e.newValue)return;try{const next=JSON.parse(e.newValue),p=profile();if(!p||next.classId===p.classId)render(next,'teacher');}catch(_){}});
  function setWeather(value){state.weather=['sunny','cloudy','rainy','thunder'].includes(value)?value:null;state.finished=false;sendState();}
  function setNote(value){state.note=String(value||'').slice(0,80);sendState();}
  function setFinished(value){state.finished=value===true;sendState();}
  window.MorningTasks={load,render,deviceId,profile,setWeather,setNote,setFinished,sendState};load();
})();
