(() => {
  const STORAGE_KEY='school-checkin:published-config', DEVICE_KEY='school-checkin:device-id', PROFILE_KEY='school-checkin:device-profile', CHANNEL_NAME='school-checkin-config';
  const DEMO_MODE=new URLSearchParams(location.search).get('demo')==='1';
  const state={config:null,completed:new Set(),socket:null,reconnectTimer:null,online:false,weather:null,note:''};
  const grid=document.getElementById('task-grid'),doneEl=document.getElementById('task-done'),totalEl=document.getElementById('task-total'),startLabel=document.getElementById('start-time-label'),endLabel=document.getElementById('end-time-label'),syncStatus=document.getElementById('sync-status'),deviceLabel=document.getElementById('device-label');
  const channel='BroadcastChannel'in window?new BroadcastChannel(CHANNEL_NAME):null;
  const safe=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]||c));
  function profile(){if(DEMO_MODE)return{classId:'1-1',deviceId:'demo-1-1-07',label:'1年1組 7番（デモ）'};try{return JSON.parse(localStorage.getItem(PROFILE_KEY)||'null');}catch(_){return null;}}
  function deviceId(){const p=profile();if(p?.deviceId){if(!DEMO_MODE)localStorage.setItem(DEVICE_KEY,p.deviceId);return p.deviceId;}let v=localStorage.getItem(DEVICE_KEY);if(!v){v=`tablet-${Math.random().toString(36).slice(2,8)}`;localStorage.setItem(DEVICE_KEY,v);}return v;}
  function paintDeviceLabel(){const p=profile();if(deviceLabel)deviceLabel.textContent=p?.label||'未設定のタブレット';}
  function progress(){const active=(state.config?.tasks||[]).filter(t=>t.enabled);return{done:active.filter(t=>state.completed.has(t.id)).length,total:active.length};}
  function sendState(){if(DEMO_MODE||state.socket?.readyState!==WebSocket.OPEN)return;const p=progress();state.socket.send(JSON.stringify({type:'student-state',deviceId:deviceId(),weather:state.weather,note:state.note.slice(0,80),done:p.done,total:p.total}));}
  function paintProgress(){const p=progress();doneEl.textContent=String(p.done);totalEl.textContent=String(p.total);window.dispatchEvent(new CustomEvent('morning-task-progress',{detail:p}));}
  function makeTaskCard(task){const b=document.createElement('button');b.className=`task-card task-${task.accent||'blue'}`;b.type='button';b.dataset.taskId=task.id;const done=state.completed.has(task.id);b.classList.toggle('done',done);b.setAttribute('aria-pressed',String(done));b.innerHTML=`<span class="task-icon">${safe(task.icon||'⭐')}</span><span class="task-copy"><span class="task-label">${safe(task.label)}</span><small>${Math.max(1,Number(task.minutes)||1)}ぷん</small></span><span class="task-check">✓</span>`;b.onclick=()=>{state.completed.has(task.id)?state.completed.delete(task.id):state.completed.add(task.id);b.classList.toggle('done',state.completed.has(task.id));b.setAttribute('aria-pressed',String(state.completed.has(task.id)));paintProgress();sendState();};return b;}
  function ack(version){if(DEMO_MODE)return;if(state.socket?.readyState===WebSocket.OPEN)state.socket.send(JSON.stringify({type:'config-ack',version:Number(version)||0,deviceId:deviceId()}));}
  function render(config,source='local'){const ids=new Set((config.tasks||[]).map(t=>t.id));state.completed=new Set([...state.completed].filter(id=>ids.has(id)));state.config=config;if(!DEMO_MODE)localStorage.setItem(STORAGE_KEY,JSON.stringify(config));grid.innerHTML='';config.tasks.filter(t=>t.enabled).forEach(t=>grid.appendChild(makeTaskCard(t)));startLabel.textContent=`${config.startTime} スタート`;endLabel.textContent=`${config.endTime} あさのかい`;document.documentElement.dataset.gradeMode=config.mode||'low';paintProgress();if(syncStatus){if(DEMO_MODE)syncStatus.textContent='デモ表示中';else if(source==='teacher')syncStatus.textContent='せんせいの へんこうを うけとりました';else syncStatus.textContent=state.online?'せんせいと つながっています':'オフラインでも つかえます';if(source==='teacher'&&!DEMO_MODE)setTimeout(()=>{syncStatus.textContent=state.online?'せんせいと つながっています':'オフラインでも つかえます';},3500);}window.dispatchEvent(new CustomEvent('morning-config-loaded',{detail:config}));sendState();}
  function connectSocket(classId){if(DEMO_MODE)return;if(!/^https?:$/.test(location.protocol)){state.online=false;return;}clearTimeout(state.reconnectTimer);if(state.socket){state.socket.onclose=null;state.socket.close();}const protocol=location.protocol==='https:'?'wss:':'ws:';const socket=new WebSocket(`${protocol}//${location.host}/ws?classId=${encodeURIComponent(classId)}&deviceId=${encodeURIComponent(deviceId())}`);state.socket=socket;socket.onopen=()=>{state.online=true;if(syncStatus)syncStatus.textContent='せんせいと つながっています';sendState();};socket.onmessage=e=>{try{const m=JSON.parse(e.data);if(m.type==='config-published'&&m.config){render(m.config,'teacher');ack(m.config.version);}else if(m.type==='hello'){if(m.config&&(!state.config||Number(m.config.version)>Number(state.config.version||0)))render(m.config,'teacher');ack((m.config||state.config||{}).version);sendState();}}catch(_){}};socket.onclose=()=>{state.online=false;if(syncStatus)syncStatus.textContent='つなぎなおしています… いまの画面はそのまま使えます';state.reconnectTimer=setTimeout(()=>connectSocket(classId),3000);};socket.onerror=()=>socket.close();}
  function readStored(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');}catch(_){return null;}}
  async function load(){paintDeviceLabel();const p=profile();if(!p&&!DEMO_MODE&&location.protocol!=='file:'){location.replace('setup.html');return;}const stored=DEMO_MODE?null:readStored(),classId=p?.classId||stored?.classId||'1-1';let config=null;if(!DEMO_MODE){try{const r=await fetch(`/api/classes/${encodeURIComponent(classId)}/today`,{cache:'no-store'});if(r.ok){config=await r.json();state.online=true;}}catch(_){}}if(!config&&stored&&(!p||stored.classId===classId))config=stored;if(!config){try{const r=await fetch('data/tasks.json',{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);config=await r.json();config.classId=classId;}catch(e){console.error(e);if(syncStatus)syncStatus.textContent='せっていを よみこめませんでした';return;}}render(config,'local');connectSocket(classId);}
  channel?.addEventListener('message',e=>{if(DEMO_MODE||e.data?.type!=='config-published'||!e.data.config)return;const p=profile();if(p&&e.data.config.classId!==p.classId)return;render(e.data.config,'teacher');});
  window.addEventListener('storage',e=>{if(DEMO_MODE)return;if(e.key===PROFILE_KEY){paintDeviceLabel();return;}if(e.key!==STORAGE_KEY||!e.newValue)return;try{const next=JSON.parse(e.newValue),p=profile();if(!p||next.classId===p.classId)render(next,'teacher');}catch(_){}});
  function setWeather(value){state.weather=['sunny','cloudy','rainy','thunder'].includes(value)?value:null;sendState();}
  function setNote(value){state.note=String(value||'').slice(0,80);sendState();}
  window.MorningTasks={load,render,deviceId,profile,setWeather,setNote,sendState};load();
})();
