(() => {
  const STORAGE_KEY='school-checkin:published-config', DEVICE_KEY='school-checkin:device-id', CHANNEL_NAME='school-checkin-config';
  const state={config:null,completed:new Set(),socket:null,reconnectTimer:null};
  const grid=document.getElementById('task-grid'),doneEl=document.getElementById('task-done'),totalEl=document.getElementById('task-total'),startLabel=document.getElementById('start-time-label'),endLabel=document.getElementById('end-time-label'),syncStatus=document.getElementById('sync-status');
  const channel='BroadcastChannel' in window?new BroadcastChannel(CHANNEL_NAME):null;
  const safe=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]||c));
  function deviceId(){let v=localStorage.getItem(DEVICE_KEY);if(!v){v=`tablet-${Math.random().toString(36).slice(2,8)}`;localStorage.setItem(DEVICE_KEY,v);}return v;}
  function paintProgress(){const active=(state.config?.tasks||[]).filter(t=>t.enabled);doneEl.textContent=String(active.filter(t=>state.completed.has(t.id)).length);totalEl.textContent=String(active.length);}
  function makeTaskCard(task){const b=document.createElement('button');b.className=`task-card task-${task.accent||'blue'}`;b.type='button';b.dataset.taskId=task.id;const done=state.completed.has(task.id);b.classList.toggle('done',done);b.setAttribute('aria-pressed',String(done));b.innerHTML=`<span class="task-icon">${safe(task.icon||'⭐')}</span><span class="task-copy"><span class="task-label">${safe(task.label)}</span><small>${Math.max(1,Number(task.minutes)||1)}ぷん</small></span><span class="task-check">✓</span>`;b.onclick=()=>{state.completed.has(task.id)?state.completed.delete(task.id):state.completed.add(task.id);b.classList.toggle('done',state.completed.has(task.id));b.setAttribute('aria-pressed',String(state.completed.has(task.id)));paintProgress();};return b;}
  function ack(version){if(state.socket?.readyState===WebSocket.OPEN)state.socket.send(JSON.stringify({type:'config-ack',version:Number(version)||0,deviceId:deviceId()}));}
  function render(config,source='local'){const ids=new Set((config.tasks||[]).map(t=>t.id));state.completed=new Set([...state.completed].filter(id=>ids.has(id)));state.config=config;localStorage.setItem(STORAGE_KEY,JSON.stringify(config));grid.innerHTML='';config.tasks.filter(t=>t.enabled).forEach(t=>grid.appendChild(makeTaskCard(t)));startLabel.textContent=`${config.startTime} スタート`;endLabel.textContent=`${config.endTime} あさのかい`;document.documentElement.dataset.gradeMode=config.mode||'low';paintProgress();if(syncStatus){syncStatus.textContent=source==='teacher'?'せんせいの へんこうを うけとりました':'このたんまつは じゅんびOK';if(source==='teacher')setTimeout(()=>{if(syncStatus.textContent.includes('へんこう'))syncStatus.textContent='せんせいと つながっています';},3500);}window.dispatchEvent(new CustomEvent('morning-config-loaded',{detail:config}));}
  function connectSocket(classId){if(!/^https?:$/.test(location.protocol))return;clearTimeout(state.reconnectTimer);if(state.socket){state.socket.onclose=null;state.socket.close();}const protocol=location.protocol==='https:'?'wss:':'ws:';const socket=new WebSocket(`${protocol}//${location.host}/ws?classId=${encodeURIComponent(classId)}&deviceId=${encodeURIComponent(deviceId())}`);state.socket=socket;socket.onopen=()=>{if(syncStatus)syncStatus.textContent='せんせいと つながっています';};socket.onmessage=e=>{try{const m=JSON.parse(e.data);if(m.type==='config-published'&&m.config){render(m.config,'teacher');ack(m.config.version);}else if(m.type==='hello'){if(m.config&&(!state.config||Number(m.config.version)>Number(state.config.version||0)))render(m.config,'teacher');ack((m.config||state.config||{}).version);if(syncStatus)syncStatus.textContent='せんせいと つながっています';}}catch(_){}};socket.onclose=()=>{if(syncStatus)syncStatus.textContent='つなぎなおしています…';state.reconnectTimer=setTimeout(()=>connectSocket(classId),3000);};socket.onerror=()=>socket.close();}
  function readStored(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');}catch(_){return null;}}
  async function load(){const stored=readStored(),classId=stored?.classId||'1-1';let config=null;try{const r=await fetch(`/api/classes/${encodeURIComponent(classId)}/today`,{cache:'no-store'});if(r.ok)config=await r.json();}catch(_){}if(!config&&stored)config=stored;if(!config){try{const r=await fetch('data/tasks.json',{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);config=await r.json();}catch(e){console.error(e);if(syncStatus)syncStatus.textContent='せっていを よみこめませんでした';return;}}render(config,'local');connectSocket(config.classId||classId);}
  channel?.addEventListener('message',e=>{if(e.data?.type!=='config-published'||!e.data.config)return;const previous=state.config?.classId;render(e.data.config,'teacher');if(e.data.config.classId&&e.data.config.classId!==previous)connectSocket(e.data.config.classId);});
  window.addEventListener('storage',e=>{if(e.key!==STORAGE_KEY||!e.newValue)return;try{render(JSON.parse(e.newValue),'teacher');}catch(_){}});
  window.MorningTasks={load,render,deviceId};load();
})();
